### ISSUE TITLE
Custom pages

### ISSUE THREAD

**Issue by niemajak900** [thebhikandeshmukh/shark#5]
is it possible to add these login pages?:

nike.com
deviantart.com
pornhub.com
teachable.com

or create some sort of custom option.

btw the tool is really great!

**Comment by ngleaderfrik** [comment]
> is it possible to add these login pages?:
> 
> nike.com deviantart.com pornhub.com teachable.com
> 
> or create some sort of custom option.
> 
> btw the tool is really great!

Hello how did you fix deceptive site ahead or someone might trick you please help

**Comment by bhikandeshmukh** [comment]
send me template

**Comment by bhikandeshmukh** [comment]
.
